##########################################################
# Lurking Menace - Configuration File                    #
# You can override values in 'lurkingmenace_custom.toml'.#
##########################################################

[Timers]
# Enable delayed explosion or spawn effects
bUseDelayedExplosion = true
# Fixed delay time in seconds (only used if range is disabled)
fDelayTime = 2.5
# Enable randomized delay between min/max values instead of fixed delay
bUseDelayTimeRanges = true
# Minimum delay in seconds (if using time ranges)
fDelayTimeMinimum = 1.0
# Maximum delay in seconds (if using time ranges)
fDelayTimeMaximum = 10.0

[Settings]
# Global spawn chance for mimic-related events (0.0 - 100.0) default is 10.0
fEventSpawnChance = 10.0

[Toggles]
# Enable generic NPC corpse spawns
bSpawnFromNpcsGeneric = true
# Enable werewolf corpse spawns
bNPCSpawnWerewolf = true
# Enable dwarven NPC corpse spawns (automatons or Dwemer constructs)
bSpawnFromDwarvenNPC = true
# Enable vampire corpse spawns
bNPCSpawnVampire = true
# Enable dragon corpse spawns
bSpawnFromDragon = false
# Enable undead corpse spawns (skeletons, draugr, etc.)
bSpawnFromUndeadNPC = true
# Enable spawns from Draugr containers (dead draugr that are actually static and never wake up)
bChestSpawnDraugr = true
# Enable Dwarven automaton spawns from containers in Dwemer ruins
bChestSpawnDwarven = true
# Enable Special spawns in warlock/vampire locations
bChestSpawnWarlock = true
# Enable generic mimic spawns from chests
bChestSpawnMimic = true
# Enable urn explosion events in dungeons
bUrnExplosions = true
# Enable explosion VFX when a spawn event happens
bUseVisualExplosions = true
# Play the meme sound effect when events trigger
bUseMemeSound = false
# Allow spawns based on custom formlists
bSpawnFromList = true
# Allow spawns from activating/hitting ore veins
bSpawnFromOreVein = true

